name: Create & Release UnityPackage

on:
  push:
    branches: |
      Release
    #  main
    
env:
  packageName: "RMU Fast Loading"

jobs:
  Create-Release-Unitypackage:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
      # Move files to "Assets/RPGMaker/Codebase/Add-ons" directory
      - run: |
          mkdir -p Assets/RPGMaker/Codebase/Add-ons
          mv FasterLoading.meta Assets/RPGMaker/Codebase/Add-ons
          mv FasterLoading Assets/RPGMaker/Codebase/Add-ons
      # Input metafiles
      - run: |
          echo "Assets/RPGMaker/Codebase/Add-ons/FasterLoading.meta" > metaList
          find Assets/RPGMaker/Codebase/Add-ons/FasterLoading/ -name \*.meta >> metaList
          
      - name: Set Environment Variables
        run: echo "unityPackage = ${{ env.packageName }}.unitypackage" >> $GITHUB_ENV
    
      - name: create-unitypackage
        # You may pin to the exact commit or the version.
        # uses: pCYSl5EDgo/create-unitypackage@cfcd3cf0391a5ef1306342794866a9897c32af0b
        uses: pCYSl5EDgo/create-unitypackage@v1.1.1
        with:
          # Output unitypackage file path
          package-path: '${{ env.unityPackage }}'
          # Relative file paths from project-folder. Multi-line string value. Each line should ends with .meta.
          include-files: metaList
          # Unity project folder. Default => ./
          #project-folder: # optional

      - name: Update release
        uses: ColinPitrat/update-release@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ env.unityPackage }}
